### ISSUE TITLE
Regex incorrect for level 1

### ISSUE THREAD

**Issue by Mathematti** [A11y-Game/A11y-Game#12]
Inputting something like this `<img alt=" src="axolotl.jpg"></img>` is correct because your regex only looks at if there is an `alt="` and then if there is an "axolotl" somewhere after that.
![image](https://github.com/A11y-Game/A11y-Game/assets/77683178/fc6c4788-65f5-437f-8575-2e273c7670ca)

**Comment by felixwollmann** [comment]
Thank you for your issue! This was resolved #15.
